CDEBUG = -g
LDEBUG = -g

PROG = CTrieTest

CPP_SRC = CTrieTest.cpp

EXTRA_CFLAGS = \
-I$(INC_DIR)/CTrie \
-I$(INC_DIR)/CFile \
-I$(INC_DIR)/CFileType \
-I$(INC_DIR)/CStrUtil \

LIBS = \
-lCFile -lCOS -lCStrUtil -lCPrintF \

include $(MAKE_DIR)/bin.mk
