CDEBUG = -g
LDEBUG = -g

PROG = CTrieTest

CPP_SRC = CTrieTest.cpp

EXTRA_CFLAGS = \
-I$(INC_DIR)/CTrie \
-I$(INC_DIR)/CFile \
-I$(INC_DIR)/CFileType \

LIBS = \
-lCFile -lCOSFile -lCOSUser -lCStrUtil -lCPrintF \

include $(MAKE_DIR)/bin.mk
