#ifndef CALIGN_TYPE_H
#define CALIGN_TYPE_H

enum CHAlignType {
  CHALIGN_TYPE_NONE,
  CHALIGN_TYPE_LEFT,
  CHALIGN_TYPE_CENTER,
  CHALIGN_TYPE_RIGHT,
  CHALIGN_TYPE_JUSTIFY,
  CHALIGN_TYPE_INSIDE,
  CHALIGN_TYPE_OUTSIDE,

  CHALIGN_TYPE_CENTRE = CHALIGN_TYPE_CENTER
};

enum CVAlignType {
  CVALIGN_TYPE_NONE,
  CVALIGN_TYPE_TOP,
  CVALIGN_TYPE_CENTER,
  CVALIGN_TYPE_BOTTOM,
  CVALIGN_TYPE_BASELINE,

  CVALIGN_TYPE_CENTRE = CVALIGN_TYPE_CENTER
};

enum CAlignType {
  CALIGN_TYPE_NONE  ,
  CALIGN_TYPE_TOP   ,
  CALIGN_TYPE_LEFT   = CALIGN_TYPE_TOP,
  CALIGN_TYPE_CENTER,
  CALIGN_TYPE_CENTRE = CALIGN_TYPE_CENTER,
  CALIGN_TYPE_MIDDLE = CALIGN_TYPE_CENTER,
  CALIGN_TYPE_BOTTOM,
  CALIGN_TYPE_RIGHT  = CALIGN_TYPE_BOTTOM
};

#endif
