#ifndef CCURSOR_H
#define CCURSOR_H

enum CCursorType {
  CURSOR_TYPE_ARROW,
  CURSOR_TYPE_TOP_LEFT_ARROW,
  CURSOR_TYPE_QUESTION_ARROW,
  CURSOR_TYPE_TOP_SIDE,
  CURSOR_TYPE_BOTTOM_SIDE,
  CURSOR_TYPE_LEFT_SIDE,
  CURSOR_TYPE_RIGHT_SIDE,
  CURSOR_TYPE_TOP_LEFT_CORNER,
  CURSOR_TYPE_TOP_RIGHT_CORNER,
  CURSOR_TYPE_BOTTOM_LEFT_CORNER,
  CURSOR_TYPE_BOTTOM_RIGHT_CORNER,
  CURSOR_TYPE_SB_LEFT_ARROW,
  CURSOR_TYPE_SB_H_DOUBLE_ARROW,
  CURSOR_TYPE_SB_V_DOUBLE_ARROW,
  CURSOR_TYPE_TOP_LEFT_ANGLE,
  CURSOR_TYPE_FLEUR,
  CURSOR_TYPE_WATCH,
  CURSOR_TYPE_CROSS_HAIR,
  CURSOR_TYPE_SKULL,
  CURSOR_TYPE_CYCLE,
  CURSOR_TYPE_SPRAY,
  CURSOR_TYPE_HAND,
  CURSOR_TYPE_MOVE,
  CURSOR_TYPE_TEXT
};

#endif
