#ifndef CGEOM_3D_TYPE_H
#define CGEOM_3D_TYPE_H

enum CGeom3DType {
  CGEOM_3D_TYPE_NONE = -1,
  CGEOM_3D_TYPE_3DS,
  CGEOM_3D_TYPE_3DRW,
  CGEOM_3D_TYPE_ASC,
  CGEOM_3D_TYPE_COB,
  CGEOM_3D_TYPE_DXF,
  CGEOM_3D_TYPE_OBJ,
  CGEOM_3D_TYPE_PLG,
  CGEOM_3D_TYPE_SCENE,
  CGEOM_3D_TYPE_V3D,
  CGEOM_3D_TYPE_X3D
};

#endif
