#ifndef CSCROLL_TYPE_H
#define CSCROLL_TYPE_H

enum CScrollType {
  CSCROLL_TYPE_NONE  ,
  CSCROLL_TYPE_TOP   ,
  CSCROLL_TYPE_LEFT   = CSCROLL_TYPE_TOP,
  CSCROLL_TYPE_CENTER,
  CSCROLL_TYPE_CENTRE = CSCROLL_TYPE_CENTER,
  CSCROLL_TYPE_MIDDLE = CSCROLL_TYPE_CENTER,
  CSCROLL_TYPE_BOTTOM,
  CSCROLL_TYPE_RIGHT  = CSCROLL_TYPE_BOTTOM,
  CSCROLL_TYPE_VISIBLE
};

#endif
