#ifndef CSHADE_TYPE_3D_H
#define CSHADE_TYPE_3D_H

enum CShadeType3D {
  CSHADE_TYPE_3D_CONSTANT,
  CSHADE_TYPE_3D_FLAT,
  CSHADE_TYPE_3D_GOURAUD,
  CSHADE_TYPE_3D_PHONG,
  CSHADE_TYPE_3D_TEXTURE
};

#endif
