#ifndef CSIDE_TYPE_H
#define CSIDE_TYPE_H

enum CSideType {
  CSIDE_TYPE_NONE   = 0,
  CSIDE_TYPE_LEFT   = (1<<0),
  CSIDE_TYPE_RIGHT  = (1<<1),
  CSIDE_TYPE_TOP    = (1<<2),
  CSIDE_TYPE_BOTTOM = (1<<3),

  CSIDE_TYPE_BOTTOM_LEFT  = (CSIDE_TYPE_BOTTOM | CSIDE_TYPE_LEFT ),
  CSIDE_TYPE_BOTTOM_RIGHT = (CSIDE_TYPE_BOTTOM | CSIDE_TYPE_RIGHT),
  CSIDE_TYPE_TOP_LEFT     = (CSIDE_TYPE_TOP    | CSIDE_TYPE_LEFT ),
  CSIDE_TYPE_TOP_RIGHT    = (CSIDE_TYPE_TOP    | CSIDE_TYPE_RIGHT),

  CSIDE_TYPE_NOT_LEFT   =
    (CSIDE_TYPE_RIGHT | CSIDE_TYPE_TOP   | CSIDE_TYPE_BOTTOM),
  CSIDE_TYPE_NOT_RIGHT  =
    (CSIDE_TYPE_LEFT  | CSIDE_TYPE_TOP   | CSIDE_TYPE_BOTTOM),
  CSIDE_TYPE_NOT_TOP    =
    (CSIDE_TYPE_LEFT  | CSIDE_TYPE_RIGHT | CSIDE_TYPE_BOTTOM),
  CSIDE_TYPE_NOT_BOTTOM =
    (CSIDE_TYPE_LEFT  | CSIDE_TYPE_RIGHT | CSIDE_TYPE_TOP   ),

  CSIDE_TYPE_VERTICAL   = (CSIDE_TYPE_LEFT | CSIDE_TYPE_RIGHT ),
  CSIDE_TYPE_HORIZONTAL = (CSIDE_TYPE_TOP  | CSIDE_TYPE_BOTTOM),

  CSIDE_TYPE_ALL =
    (CSIDE_TYPE_LEFT | CSIDE_TYPE_RIGHT | CSIDE_TYPE_TOP | CSIDE_TYPE_BOTTOM)
};

#endif
